services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"